language: java
before_install:
  - npm install -g bower
install: "./gradlew classes"
script:
  - "./gradlew test -DjunitVersion=4.9"
  - "./gradlew test -DjunitVersion=4.10"
  - "./gradlew test -DjunitVersion=4.11"
  - "./gradlew test -DjunitVersion=4.12"
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
after_success:
  - "./gradlew overallJacocoReport coveralls"
