language: java
install: "gradle classes"
script:
  - "gradle test -DjunitVersion=4.9"
  - "gradle test -DjunitVersion=4.10"
  - "gradle test -DjunitVersion=4.11"
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
after_success:
  - gradle overallJacocoReport coveralls
